#! /usr/bin/env bash

if [ -z $DBUS_SESSION_BUS_ADDRESS ]
then
    # This is needed to run gsettings from cron. Slightly modified code from:
    # http://askubuntu.com/a/484752.
    PID=$(pgrep -u $(whoami) mate-session)
    if [ -z $PID ]
    then
        # If mate-session didn't yield any result, try gnome-session.
        PID=$(pgrep -u $(whoami) gnome-session)
    fi
    export DBUS_SESSION_BUS_ADDRESS=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/$PID/environ|cut -d= -f2-)
fi

# Set the path below to where Common Desktop is.
cd /path/to/common-desktop
./common_desktop.py $*
